<?xml version="1.0" encoding="UTF-8" ?>
<testsuites disabled="0" errors="0" failures="1" tests="2" time="9.494">
 <testsuite name="A suite with some shared setup" timestamp="2020-01-20T11:40:04" hostname="localhost" time="9.494" errors="0" tests="2" skipped="0" disabled="0" failures="1">
  <testcase classname="A suite with some shared setup" name="First one is awesome!" time="9.485" />
  <testcase classname="A suite with some shared setup" name="Second test should fail" time="0.004">
   <failure type="toEqual" message="Expected 9 to equal 10."><![CDATA[Error: Failed expectation
    at UserContext.<anonymous> (/Users/aserra/Documents/Automation-Training/specs/simple.2spec.js:10:28)
    at /Users/aserra/.nvm/versions/node/v8.12.0/lib/node_modules/protractor/node_modules/jasminewd2/index.js:112:25
    at new ManagedPromise (/Users/aserra/.nvm/versions/node/v8.12.0/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:1077:7)
    at ControlFlow.promise (/Users/aserra/.nvm/versions/node/v8.12.0/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2505:12)
    at schedulerExecute (/Users/aserra/.nvm/versions/node/v8.12.0/lib/node_modules/protractor/node_modules/jasminewd2/index.js:95:18)
    at TaskQueue.execute_ (/Users/aserra/.nvm/versions/node/v8.12.0/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:3084:14)
    at TaskQueue.executeNext_ (/Users/aserra/.nvm/versions/node/v8.12.0/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:3067:27)
    at asyncRun (/Users/aserra/.nvm/versions/node/v8.12.0/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2974:25)
    at /Users/aserra/.nvm/versions/node/v8.12.0/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:668:7]]>
   </failure>
  </testcase>
 </testsuite>
</testsuites>